### PR TITLE
Resource names are aliases for claiming them

### PR DESCRIPTION
**Pull request by johnapost**
Aliases commands like `/snaggg af-prod` to the claim command `/snaggg claim af-prod`. Thinking we can also have it alias to `/snaggg release af-prod` if the resource is already claimed by the user.

The workflow is currently `/snaggg claim af-prod` then `/snaggg release af-prod`.
It could possibly be `/snaggg af-prod` then `/snaggg af-prod`.

### Notes
Wanted to write a test for this but it looks like the code would have to be refactored to be more easily testable.

I started down that path but didn't want to go through the trouble of messing with the bot locally so I decided to put this up and see what you thought.

### CODE REVIEW

**Comment by chrisbodhi** [comment]
I like this! Let's chat about how to test that `index.js` file, because I can do better with that.

**Comment by johnapost** [comment]
@chrisbodhi, would you want me to fix this up to handle releasing the resource as well?

**Comment by chrisbodhi** [comment]
Yeah, that behavior sounds like it would be more consistent. Thanks, @johnapost!

**Comment by johnapost** [comment]
@chrisbodhi, hey uh I still haven't tested this locally but it should work. I added a helper function and am using that to check if the user has already claimed a resource.

Would you mind testing this?

**Comment by johnapost** [comment]
lmao, i will never finish this

**Comment by chrisbodhi** [comment]
lololol, that's fair. 😁

**Pull request closed without merging**
